### ISSUE TITLE
Integrate into eido?

### ISSUE THREAD

**Issue by nsheff** [pepkit/pepconvert#1]
I propose the functionality here be integrated into eido. The reason is: all `pepconvert` provides is ability to output a PEP in some other format. It seems like we'd also want it to do validation, so eido is a critical part of this. And it kind of fits into the mantra of "eido is the CLI for PEPs". It broadens the original view of eido as providing validation only, to eido being validation/manipulation -- which I think still fits with the original vision for eido as the keeper of the "forms of PEP" -- it just becomes more powerful because it doesn't just *check* them, but can manipulate them.

Opinions, @stolarczyk or @afrendeiro?

**Comment by stolarczyk** [comment]
it has been integrated into eido
